# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('Entrepreneurship', 'Entrepreneurship'), ('Politics', 'Politics'), ('Personal development', 'Personal development'), ('Startups', 'Startups'), ('Religion', 'Religion')], max_length=40)),
                ('data_created', models.DateField(auto_now_add=True)),
                ('image', models.FileField(upload_to='media/')),
                ('views', models.PositiveIntegerField(blank=True, default=0)),
                ('shares', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sender', models.CharField(blank=True, max_length=100, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smghApi.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('category', models.CharField(choices=[('Entrepreneurship', 'Entrepreneurship'), ('Politics', 'Politics'), ('Personal development', 'Personal development'), ('Startups', 'Startups'), ('Religion', 'Religion')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sender', models.CharField(blank=True, max_length=100, null=True)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smghApi.Discussion')),
            ],
        ),
    ]
