# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smghApi', '0004_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
