# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smghApi', '0005_article_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='athor',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
