# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smghApi', '0006_auto_20170723_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
