# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smghApi', '0009_auto_20170723_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='data_created',
            field=models.DateField(auto_now=True),
        ),
    ]
